### PR TITLE
fix i686 builds

### PR DESCRIPTION
**Pull request by cstkingkey**

### CODE REVIEW

**Comment by shepmaster** [comment]
Can you explain a bit more about how to reproduce the problem? I _think_ I [added a 686 build](https://github.com/shepmaster/jetscii/runs/6331391470), but it's green, so I'm not following what is currently broken.

**Comment by cstkingkey** [comment]
when avx feature is enabled for x86 builds, both the fallback and simd implements are disabled which leads to build failure.

**Comment by shepmaster** [comment]
> when avx feature is enabled

We don't use that feature; do you mean `sse4.2`? Can you tell me which processor is 32-bit and has SSE4.2 support?

**Comment by cstkingkey** [comment]
> > when avx feature is enabled
> 
> We don't use that feature; do you mean `sse4.2`? Can you tell me which processor is 32-bit and has SSE4.2 support?

maybe avx imply sse4.2?
32bit software can use avx or sse instruments. it's cpu hardware arch related. in other words, 32bit software can run on 64bit platforms and i
686 here means software arch.

**Comment by shepmaster** [comment]
Thanks! Can you confirm that [this](https://github.com/shepmaster/jetscii/runs/6337557690?check_suite_focus=true) is what you see when the code fails to compile? If so, could you also check that [this branch](https://github.com/shepmaster/jetscii/tree/32bit-sse42) fixes your problem? This uses the SSE4.2 code, even if the processor is x86 and not x86_64.

**Comment by cstkingkey** [comment]
`rustc --print cfg -C target-feature=+avx`
outputs
`target_feature="sse4.2"`

so enable avx feature will also enable sse4.2.

**Comment by cstkingkey** [comment]
> Thanks! Can you confirm that [this](https://github.com/shepmaster/jetscii/runs/6337557690?check_suite_focus=true) is what you see when the code fails to compile? If so, could you also check that [this branch](https://github.com/shepmaster/jetscii/tree/32bit-sse42) fixes your problem? This uses the SSE4.2 code, even if the processor is x86 and not x86_64.

yes and yes.

**Comment by shepmaster** [comment]
In that case, what do you think about closing this in favor of #52?

**Comment by cstkingkey** [comment]
> In that case, what do you think about closing this in favor of #52?

it's ok.

**Comment by shepmaster** [comment]
Released in [0.5.2](https://crates.io/crates/jetscii/0.5.2)

**Pull request closed without merging**
